const Images = {
  Logo: require('../images/center_logo.png'),
  dashboard: require('../images/dashboard.png'),
  HeaderLogo: require('../images/logoHeader.png'),
  NoInternet: require('../images/noConnection.png'),
  PlaceHolder: require('../images/placeholder.png'),
  BackgroundImage: require('../images/background.png'),
  MMImage: require('../images/margmaker.png'),
  SNB: require('../images/snb.png'),
  Ecomdio: require('../images/ecomdio.jpg'),

  //mainImages

  Account: require('../assets/image/Account.svg'),
  Accounts: require('../assets/image/accounts.svg'),
  Arrow: require('../assets/image/arrow.svg'),
  BackArrow: require('../assets/image/back-arrow.svg'),
  Bol_logo__1_: require('../assets/image/bol_logo__1_.png'),
  Calendar: require('../assets/image/calendar.svg'),
  // chatBubbles: require('../assets/image/chat-bubbles-with-ellipsis.svg'),
  clientsLogo: require('../assets/image/clients-logo.png'),
  Commentary: require('../assets/image/commentary.svg'),
  Email: require('../assets/image/email.svg'),
  Facebook: require('../assets/image/facebook.svg'),
  Google: require('../assets/image/google.svg'),
  Home: require('../assets/image/home.svg'),
  HomeSelected: require('../assets/image/home-selected.svg'),
  horse1: require('../assets/image/horse-1.png'),
  hotlineP: require('../assets/image/hotline.png'),
  Hotline: require('../assets/image/hotline.svg'),
  incidentP: require('../assets/image/incident.png'),
  Incident: require('../assets/image/incident.svg'),
  Jocky: require('../assets/image/jocky.svg'),
  lineChart: require('../assets/image/line-chart.png'),
  Lock: require('../assets/image/lock.svg'),
  MultiSelection: require('../assets/image/multi-selection.svg'),
  Oops: require('../assets/image/oops.svg'),
  otpHeading: require('../assets/image/otpHeading.png'),
  OtpHeadingCenter: require('../assets/image/otpHeading_center.svg'),
  passwordIcons: require('../assets/image/password-icons.png'),
  Phone: require('../assets/image/phone.svg'),
  raceP: require('../assets/image/race.png'),
  Race: require('../assets/image/race.svg'),
  raceDetailHeader: require('../assets/image/raceDetailHeader.png'),
  scrn1: require('../assets/image/scrn1.png'),
  Selection: require('../assets/image/selection.svg'),
  selectionWhite: require('../assets/image/selection-white.svg'),
  shape: require('../assets/image/shape.svg'),
  signinHeadingP: require('../assets/image/signinHeading.png'),
  signinHeadingCenter: require('../assets/image/signinHeading_center.svg'),
  signupHeading: require('../assets/image/signupHeading.png'),
  signupHeading_center: require('../assets/image/signupHeading_center.svg'),
  slider: require('../assets/image/slider.png'),
  swimmingP: require('../assets/image/swimming.png'),
  swimming: require('../assets/image/swimming.svg'),
  termsBg: require('../assets/image/terms-bg.png'),
  trackP: require('../assets/image/track.png'),
  track: require('../assets/image/track.svg'),
  trainerP: require('../assets/image/trainer.png'),
  trainer: require('../assets/image/trainer.svg'),
  trophyG: require('../assets/image/trophy.gif'),
  trophy: require('../assets/image/trophy.svg'),
  upcomingBg: require('../assets/image/upcoming-bg.png'),
  user: require('../assets/image/user.svg'),
  website: require('../assets/image/website.svg'),
  update: require('../assets/image/update.png'),
  otp: require('../assets/image/otp.jpg'),
  otp1: require('../assets/image/Otp2.jpg')
}
export default Images
